"use client";

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import {
  buildExportFileName,
  buildTakeInsights,
  inferExtensionFromMimeType,
  pickSupportedMimeType,
  readStoredSelfTapeTakes,
  SELF_TAPE_STORAGE_KEY,
  supportsMediaCapture,
  writeStoredSelfTapeTakes,
  type PersistedSelfTapeTake,
} from "../../lib/self-tape";

type ActiveTool =
  | "teleprompter"
  | "recorder"
  | "comparison"
  | "notes"
  | "export";
type CameraState = "idle" | "requesting" | "ready" | "error";
type NotificationState = {
  type: "success" | "error" | "info";
  message: string;
} | null;
type NoteType =
  | "emotion"
  | "delivery"
  | "timing"
  | "movement"
  | "improvement";
type NoteSeverity = "positive" | "neutral" | "needs_work";

interface TakeNote {
  id: string;
  timestamp: number;
  type: NoteType;
  content: string;
  severity: NoteSeverity;
  autoGenerated: boolean;
}

interface Take extends PersistedSelfTapeTake {
  notes: TakeNote[];
  videoUrl?: string;
}

interface TeleprompterSettings {
  speed: number;
  fontSize: number;
  mirrorMode: boolean;
  highlightCurrentLine: boolean;
  autoScroll: boolean;
  countdownSeconds: number;
}

interface ExportSettings {
  quality: "casting" | "high" | "medium";
  format: "mp4" | "mov" | "webm";
  includeSlate: boolean;
  slateDuration: number;
  actorName: string;
  projectName: string;
  roleName: string;
  agencyName: string;
}

interface ComparisonView {
  leftTakeId: string | null;
  rightTakeId: string | null;
  syncPlayback: boolean;
}

interface PendingTake {
  id: string;
  name: string;
  recordedAt: string;
  mimeType: string;
  teleprompterUsed: boolean;
}

const RECORDING_MIME_CANDIDATES = [
  "video/webm;codecs=vp9,opus",
  "video/webm;codecs=vp8,opus",
  "video/webm",
];

const NOTE_TYPE_LABELS: Record<NoteType, string> = {
  emotion: "💫 عاطفة",
  delivery: "🎤 إلقاء",
  timing: "⏱️ توقيت",
  movement: "🎭 حركة",
  improvement: "💡 تحسين",
};

const NOTE_TYPE_COLOR: Record<NoteType, string> = {
  emotion: "bg-pink-500/20 text-pink-300",
  delivery: "bg-blue-500/20 text-blue-300",
  timing: "bg-purple-500/20 text-purple-300",
  movement: "bg-orange-500/20 text-orange-300",
  improvement: "bg-cyan-500/20 text-cyan-300",
};

const SAMPLE_SCRIPT = `المشهد الأول - غرفة المعيشة - نهاراً

تدخل سارة الغرفة بخطوات متثاقلة، تحمل في يدها رسالة مفتوحة.

سارة: (تنظر للرسالة بصدمة)
لا... هذا لا يمكن أن يكون حقيقياً.
كيف يمكنه أن يفعل هذا بعد كل هذه السنوات؟

(تجلس على الأريكة، تمسك الرسالة بيدين مرتجفتين)

سارة: (بصوت مختنق)
ظننت أننا كنا عائلة...
ظننت أن الماضي قد انتهى.

(تنهض فجأة، تمشي نحو النافذة)

سارة: (بحزم)
لكنني لن أسمح لهذا أن يدمر ما بنيته.
لقد تغيرت... وسأثبت ذلك.`;

const SAMPLE_TAKES: Take[] = [
  {
    id: "sample-1",
    name: "Take 1 - أولي",
    duration: 125,
    recordedAt: "2025-01-15T10:30:00.000Z",
    notes: [
      {
        id: "sample-1-note-1",
        timestamp: 15,
        type: "emotion",
        content: "افتتاحية عاطفية قوية والصدمة مقروءة بصرياً.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-1-note-2",
        timestamp: 45,
        type: "timing",
        content: "يمكن إبطاء الإيقاع هنا قليلاً قبل الجملة الحاسمة.",
        severity: "needs_work",
        autoGenerated: true,
      },
      {
        id: "sample-1-note-3",
        timestamp: 92,
        type: "movement",
        content: "الانتقال نحو النافذة يخدم التصعيد جيداً.",
        severity: "positive",
        autoGenerated: true,
      },
    ],
    score: 78,
    status: "completed",
    source: "sample",
  },
  {
    id: "sample-2",
    name: "Take 2 - تحسين",
    duration: 132,
    recordedAt: "2025-01-15T10:45:00.000Z",
    notes: [
      {
        id: "sample-2-note-1",
        timestamp: 20,
        type: "emotion",
        content: "عمق عاطفي ممتاز في لحظة الانكسار الأولى.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-2-note-2",
        timestamp: 52,
        type: "timing",
        content: "الوقفة هنا مؤثرة ومضبوطة.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-2-note-3",
        timestamp: 100,
        type: "improvement",
        content: "النهاية تحتاج طبقة حسم أكثر وضوحاً.",
        severity: "neutral",
        autoGenerated: true,
      },
    ],
    score: 85,
    status: "completed",
    source: "sample",
  },
  {
    id: "sample-3",
    name: "Take 3 - نهائي",
    duration: 128,
    recordedAt: "2025-01-15T11:00:00.000Z",
    notes: [
      {
        id: "sample-3-note-1",
        timestamp: 18,
        type: "emotion",
        content: "الصدق العاطفي حاضر من البداية حتى الخاتمة.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-3-note-2",
        timestamp: 58,
        type: "delivery",
        content: "التلوين النغمي متوازن ويخدم الرهان الدرامي.",
        severity: "positive",
        autoGenerated: true,
      },
      {
        id: "sample-3-note-3",
        timestamp: 96,
        type: "movement",
        content: "لغة الجسد واضحة ومنضبطة داخل الكادر.",
        severity: "positive",
        autoGenerated: true,
      },
    ],
    score: 92,
    status: "completed",
    source: "sample",
  },
];

function delay(milliseconds: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function cloneSampleTakes(): Take[] {
  return SAMPLE_TAKES.map((take) => ({
    ...take,
    notes: take.notes.map((note) => ({ ...note })),
  }));
}

function formatTime(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const remainder = seconds % 60;
  return `${minutes.toString().padStart(2, "0")}:${remainder
    .toString()
    .padStart(2, "0")}`;
}

function formatRecordedAt(value: string): string {
  return new Date(value).toLocaleString("ar-EG", {
    hour: "2-digit",
    minute: "2-digit",
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

function toPersistedTake(take: Take): PersistedSelfTapeTake {
  const { videoUrl: _videoUrl, ...persistedTake } = take;
  return persistedTake;
}

function createNotesFromInsights(
  notes: Array<{
    type: "timing" | "delivery" | "improvement";
    severity: NoteSeverity;
    content: string;
  }>,
  duration: number,
): TakeNote[] {
  const safeDuration = Math.max(duration, 1);
  const slots = Math.max(notes.length, 1);

  return notes.map((note, index) => ({
    id: `note-${Date.now()}-${index}`,
    timestamp: clamp(
      Math.round((safeDuration / slots) * (index + 0.5)),
      0,
      safeDuration,
    ),
    type: note.type,
    severity: note.severity,
    content: note.content,
    autoGenerated: true,
  }));
}

function getSeverityContainerClass(severity: NoteSeverity): string {
  switch (severity) {
    case "positive":
      return "bg-green-500/10 border-green-500/30";
    case "needs_work":
      return "bg-yellow-500/10 border-yellow-500/30";
    default:
      return "bg-slate-900/50 border-purple-500/30";
  }
}

function getScoreColor(score: number | undefined): string {
  if (!score) {
    return "text-gray-400";
  }

  if (score >= 85) {
    return "text-green-400";
  }

  if (score >= 70) {
    return "text-yellow-400";
  }

  return "text-red-400";
}

function loadInitialTakes(): Take[] {
  const fallback = cloneSampleTakes().map(toPersistedTake);
  return readStoredSelfTapeTakes(fallback).map((take) => ({
    ...take,
    notes: take.notes.map((note) => ({ ...note })),
  }));
}

export const SelfTapeSuite: React.FC = () => {
  const [activeTool, setActiveTool] = useState<ActiveTool>("teleprompter");
  const [scriptText, setScriptText] = useState(SAMPLE_SCRIPT);
  const [takes, setTakes] = useState<Take[]>(loadInitialTakes);
  const [notification, setNotification] = useState<NotificationState>(null);
  const [teleprompterSettings, setTeleprompterSettings] =
    useState<TeleprompterSettings>({
      speed: 50,
      fontSize: 32,
      mirrorMode: false,
      highlightCurrentLine: true,
      autoScroll: true,
      countdownSeconds: 5,
    });
  const [teleprompterRunning, setTeleprompterRunning] = useState(false);
  const [teleprompterPosition, setTeleprompterPosition] = useState(0);
  const [countdown, setCountdown] = useState(0);
  const [cameraState, setCameraState] = useState<CameraState>("idle");
  const [cameraError, setCameraError] = useState("");
  const [isRecording, setIsRecording] = useState(false);
  const [isFinalizingTake, setIsFinalizingTake] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [comparisonView, setComparisonView] = useState<ComparisonView>({
    leftTakeId: null,
    rightTakeId: null,
    syncPlayback: true,
  });
  const [exportSettings, setExportSettings] = useState<ExportSettings>({
    quality: "casting",
    format: "webm",
    includeSlate: true,
    slateDuration: 5,
    actorName: "",
    projectName: "",
    roleName: "",
    agencyName: "",
  });
  const [exportingTakeId, setExportingTakeId] = useState<string | null>(null);
  const [exportProgress, setExportProgress] = useState(0);
  const [notesTakeId, setNotesTakeId] = useState<string | null>(null);
  const [manualNoteDrafts, setManualNoteDrafts] = useState<
    Record<string, string>
  >({});
  const [manualNoteTypes, setManualNoteTypes] = useState<
    Record<string, NoteType>
  >({});

  const previewVideoRef = useRef<HTMLVideoElement | null>(null);
  const recordingIntervalRef = useRef<ReturnType<typeof setInterval> | null>(
    null,
  );
  const teleprompterIntervalRef = useRef<ReturnType<typeof setInterval> | null>(
    null,
  );
  const countdownIntervalRef = useRef<ReturnType<typeof setInterval> | null>(
    null,
  );
  const mediaStreamRef = useRef<MediaStream | null>(null);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const recordedChunksRef = useRef<Blob[]>([]);
  const recordingTimeRef = useRef(0);
  const pendingTakeRef = useRef<PendingTake | null>(null);
  const blobRegistryRef = useRef<Map<string, Blob>>(new Map());
  const sessionUrlRegistryRef = useRef<Map<string, string>>(new Map());

  const mediaCaptureSupported = supportsMediaCapture();
  const availableTakes = useMemo(
    () => takes.filter((take) => take.status !== "recording"),
    [takes],
  );
  const totalDuration = useMemo(
    () => availableTakes.reduce((sum, take) => sum + take.duration, 0),
    [availableTakes],
  );
  const bestScore = useMemo(
    () => Math.max(...availableTakes.map((take) => take.score ?? 0), 0),
    [availableTakes],
  );
  const bestExportableTake = useMemo(() => {
    return [...availableTakes]
      .filter((take) => blobRegistryRef.current.has(take.id))
      .sort((left, right) => (right.score ?? 0) - (left.score ?? 0))[0];
  }, [availableTakes]);
  const promptLines = useMemo(
    () =>
      scriptText
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean),
    [scriptText],
  );
  const currentPromptLine = useMemo(() => {
    if (promptLines.length === 0) {
      return "أدخل نصاً لعرضه على التلقين.";
    }

    const lineIndex = clamp(
      Math.floor((teleprompterPosition / 100) * promptLines.length),
      0,
      promptLines.length - 1,
    );
    return promptLines[lineIndex] ?? promptLines[0] ?? "";
  }, [promptLines, teleprompterPosition]);

  useEffect(() => {
    recordingTimeRef.current = recordingTime;
  }, [recordingTime]);

  useEffect(() => {
    writeStoredSelfTapeTakes(takes.map(toPersistedTake));
  }, [takes]);

  useEffect(() => {
    if (!notification) {
      return undefined;
    }

    const timeoutId = setTimeout(() => setNotification(null), 4500);
    return () => clearTimeout(timeoutId);
  }, [notification]);

  useEffect(() => {
    if (availableTakes.length === 0) {
      setNotesTakeId(null);
      return;
    }

    setNotesTakeId((current) => {
      if (current && availableTakes.some((take) => take.id === current)) {
        return current;
      }
      return availableTakes[0]?.id ?? null;
    });
  }, [availableTakes]);

  useEffect(() => {
    const takeIds = new Set(availableTakes.map((take) => take.id));

    setComparisonView((current) => {
      const nextLeft =
        current.leftTakeId && takeIds.has(current.leftTakeId)
          ? current.leftTakeId
          : availableTakes[0]?.id ?? null;
      const nextRight =
        current.rightTakeId && takeIds.has(current.rightTakeId)
          ? current.rightTakeId
          : availableTakes.find((take) => take.id !== nextLeft)?.id ?? null;

      if (
        nextLeft === current.leftTakeId &&
        nextRight === current.rightTakeId
      ) {
        return current;
      }

      return {
        ...current,
        leftTakeId: nextLeft,
        rightTakeId: nextRight,
      };
    });
  }, [availableTakes]);

  useEffect(() => {
    if (!teleprompterRunning || !teleprompterSettings.autoScroll) {
      if (teleprompterIntervalRef.current) {
        clearInterval(teleprompterIntervalRef.current);
        teleprompterIntervalRef.current = null;
      }
      return undefined;
    }

    teleprompterIntervalRef.current = setInterval(() => {
      setTeleprompterPosition((previous) => {
        const nextPosition = previous + teleprompterSettings.speed / 500;
        if (nextPosition >= 100) {
          setTeleprompterRunning(false);
          return 100;
        }
        return nextPosition;
      });
    }, 100);

    return () => {
      if (teleprompterIntervalRef.current) {
        clearInterval(teleprompterIntervalRef.current);
        teleprompterIntervalRef.current = null;
      }
    };
  }, [
    teleprompterRunning,
    teleprompterSettings.autoScroll,
    teleprompterSettings.speed,
  ]);

  const showNotification = useCallback(
    (type: "success" | "error" | "info", message: string) => {
      setNotification({ type, message });
    },
    [],
  );

  const clearCountdownInterval = useCallback(() => {
    if (countdownIntervalRef.current) {
      clearInterval(countdownIntervalRef.current);
      countdownIntervalRef.current = null;
    }
  }, []);

  const clearRecordingInterval = useCallback(() => {
    if (recordingIntervalRef.current) {
      clearInterval(recordingIntervalRef.current);
      recordingIntervalRef.current = null;
    }
  }, []);

  const stopCameraTracks = useCallback((stream?: MediaStream | null) => {
    stream?.getTracks().forEach((track) => {
      track.stop();
    });
  }, []);

  const revokeTakeResources = useCallback((takeId: string) => {
    const sessionUrl = sessionUrlRegistryRef.current.get(takeId);
    if (sessionUrl) {
      URL.revokeObjectURL(sessionUrl);
      sessionUrlRegistryRef.current.delete(takeId);
    }
    blobRegistryRef.current.delete(takeId);
  }, []);

  const stopTeleprompter = useCallback(() => {
    clearCountdownInterval();
    setCountdown(0);
    setTeleprompterRunning(false);
    if (teleprompterIntervalRef.current) {
      clearInterval(teleprompterIntervalRef.current);
      teleprompterIntervalRef.current = null;
    }
  }, [clearCountdownInterval]);

  const resetTeleprompter = useCallback(() => {
    stopTeleprompter();
    setTeleprompterPosition(0);
  }, [stopTeleprompter]);

  const startTeleprompter = useCallback(() => {
    clearCountdownInterval();

    if (teleprompterSettings.countdownSeconds <= 0) {
      setCountdown(0);
      setTeleprompterRunning(true);
      return;
    }

    setTeleprompterRunning(false);
    setCountdown(teleprompterSettings.countdownSeconds);
    countdownIntervalRef.current = setInterval(() => {
      setCountdown((previous) => {
        if (previous <= 1) {
          clearCountdownInterval();
          setTeleprompterRunning(true);
          return 0;
        }
        return previous - 1;
      });
    }, 1000);
  }, [clearCountdownInterval, teleprompterSettings.countdownSeconds]);

  const attachStreamToPreview = useCallback(async (stream: MediaStream) => {
    const preview = previewVideoRef.current;
    if (!preview) {
      return;
    }

    preview.srcObject = stream;
    preview.muted = true;
    preview.playsInline = true;

    try {
      await preview.play();
    } catch {
      // لا نرفع خطأ لأن بعض بيئات الاختبار تمنع التشغيل التلقائي.
    }
  }, []);

  const requestCameraAccess = useCallback(async (): Promise<MediaStream | null> => {
    if (
      typeof navigator === "undefined" ||
      !navigator.mediaDevices?.getUserMedia
    ) {
      const errorMessage =
        "هذه البيئة لا تدعم الوصول المباشر إلى الكاميرا والميكروفون.";
      setCameraState("error");
      setCameraError(errorMessage);
      showNotification("error", errorMessage);
      return null;
    }

    setCameraState("requesting");
    setCameraError("");

    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: {
          facingMode: "user",
          width: { ideal: 1280 },
          height: { ideal: 720 },
        },
        audio: true,
      });
      stopCameraTracks(mediaStreamRef.current);
      mediaStreamRef.current = stream;
      await attachStreamToPreview(stream);
      setCameraState("ready");
      showNotification("success", "تم تفعيل الكاميرا والميكروفون بنجاح.");
      return stream;
    } catch {
      const errorMessage =
        "تعذر الوصول إلى الكاميرا أو الميكروفون. تحقق من الأذونات ثم أعد المحاولة.";
      setCameraState("error");
      setCameraError(errorMessage);
      showNotification("error", errorMessage);
      return null;
    }
  }, [attachStreamToPreview, showNotification, stopCameraTracks]);

  useEffect(() => {
    if (activeTool === "recorder" && cameraState === "idle") {
      void requestCameraAccess();
    }
  }, [activeTool, cameraState, requestCameraAccess]);

  useEffect(() => {
    if (mediaStreamRef.current) {
      void attachStreamToPreview(mediaStreamRef.current);
    }
  }, [activeTool, attachStreamToPreview]);

  useEffect(() => {
    return () => {
      clearCountdownInterval();
      clearRecordingInterval();
      if (teleprompterIntervalRef.current) {
        clearInterval(teleprompterIntervalRef.current);
      }
      if (mediaRecorderRef.current?.state === "recording") {
        try {
          mediaRecorderRef.current.stop();
        } catch {
          // تجاهل أخطاء الإيقاف أثناء التفكيك.
        }
      }
      stopCameraTracks(mediaStreamRef.current);
      mediaStreamRef.current = null;
      sessionUrlRegistryRef.current.forEach((url) => {
        URL.revokeObjectURL(url);
      });
      sessionUrlRegistryRef.current.clear();
      blobRegistryRef.current.clear();
    };
  }, [clearCountdownInterval, clearRecordingInterval, stopCameraTracks]);

  const finalizeRecordedTake = useCallback(
    (pendingTake: PendingTake) => {
      const duration = Math.max(recordingTimeRef.current, 1);
      const primaryChunk = recordedChunksRef.current[0];
      const blob =
        recordedChunksRef.current.length > 0
          ? new Blob(recordedChunksRef.current, {
              type: pendingTake.mimeType || primaryChunk?.type || "video/webm",
            })
          : null;
      const videoUrl =
        blob && typeof URL.createObjectURL === "function"
          ? URL.createObjectURL(blob)
          : undefined;

      if (blob && videoUrl) {
        blobRegistryRef.current.set(pendingTake.id, blob);
        sessionUrlRegistryRef.current.set(pendingTake.id, videoUrl);
      }

      const insights = buildTakeInsights({
        durationSeconds: duration,
        scriptText,
        teleprompterUsed: pendingTake.teleprompterUsed,
        hadRetake: takes.some((take) => take.source === "captured"),
      });

      const take: Take = {
        id: pendingTake.id,
        name: pendingTake.name,
        duration,
        recordedAt: pendingTake.recordedAt,
        notes: createNotesFromInsights(insights.notes, duration),
        score: insights.score,
        status: "completed",
        mimeType: blob?.type || pendingTake.mimeType,
        source: "captured",
        videoUrl,
      };

      setTakes((previous) => [take, ...previous]);
      setNotesTakeId(take.id);
      setComparisonView((previous) => ({
        ...previous,
        leftTakeId: take.id,
        rightTakeId:
          previous.leftTakeId && previous.leftTakeId !== take.id
            ? previous.leftTakeId
            : previous.rightTakeId && previous.rightTakeId !== take.id
              ? previous.rightTakeId
              : previous.leftTakeId,
      }));
      setIsFinalizingTake(false);
      pendingTakeRef.current = null;
      recordedChunksRef.current = [];

      if (blob) {
        showNotification(
          "success",
          `تم حفظ ${take.name} وتوليد تقييمه المحلي بنجاح.`,
        );
        return;
      }

      showNotification(
        "error",
        "انتهى التسجيل لكن المتصفح لم يسلم ملف فيديو قابلاً للتصدير.",
      );
    },
    [scriptText, showNotification, takes],
  );

  const startRecording = useCallback(async () => {
    if (!scriptText.trim()) {
      showNotification("error", "أدخل نصاً قبل بدء التسجيل.");
      return;
    }

    if (isRecording || isFinalizingTake) {
      return;
    }

    let stream = mediaStreamRef.current;
    if (!stream) {
      stream = await requestCameraAccess();
    }

    if (!stream) {
      return;
    }

    if (typeof MediaRecorder === "undefined") {
      showNotification(
        "error",
        "المتصفح الحالي لا يدعم MediaRecorder، لذا لا يمكن تسجيل فيديو فعلي.",
      );
      return;
    }

    const preferredMimeType = pickSupportedMimeType(RECORDING_MIME_CANDIDATES);
    let recorder: MediaRecorder;

    try {
      recorder = preferredMimeType
        ? new MediaRecorder(stream, { mimeType: preferredMimeType })
        : new MediaRecorder(stream);
    } catch {
      recorder = new MediaRecorder(stream);
    }

    recordedChunksRef.current = [];
    clearRecordingInterval();
    setRecordingTime(0);
    recordingTimeRef.current = 0;

    const takeNumber =
      takes.filter((take) => take.source === "captured").length + 1;
    const pendingTake: PendingTake = {
      id: `take-${Date.now()}`,
      name: `Take ${takeNumber}`,
      recordedAt: new Date().toISOString(),
      mimeType: recorder.mimeType || preferredMimeType,
      teleprompterUsed: teleprompterSettings.autoScroll,
    };

    pendingTakeRef.current = pendingTake;
    recorder.ondataavailable = (event: BlobEvent) => {
      if (event.data && event.data.size > 0) {
        recordedChunksRef.current.push(event.data);
      }
    };
    recorder.onstop = () => {
      if (pendingTakeRef.current) {
        finalizeRecordedTake(pendingTakeRef.current);
      }
    };
    recorder.onerror = () => {
      pendingTakeRef.current = null;
      recordedChunksRef.current = [];
      setIsRecording(false);
      setIsFinalizingTake(false);
      showNotification("error", "تعذر إتمام التسجيل. حاول مرة أخرى.");
    };

    try {
      recorder.start(1000);
      mediaRecorderRef.current = recorder;
      setIsRecording(true);
      setIsFinalizingTake(false);
      startTeleprompter();
      recordingIntervalRef.current = setInterval(() => {
        setRecordingTime((previous) => {
          const next = previous + 1;
          recordingTimeRef.current = next;
          return next;
        });
      }, 1000);
      showNotification("info", "بدأ التسجيل الفعلي ويمكنك إنهاؤه متى شئت.");
    } catch {
      pendingTakeRef.current = null;
      showNotification(
        "error",
        "فشل بدء التسجيل في هذه البيئة رغم توفر الكاميرا.",
      );
    }
  }, [
    clearRecordingInterval,
    finalizeRecordedTake,
    isFinalizingTake,
    isRecording,
    requestCameraAccess,
    scriptText,
    showNotification,
    startTeleprompter,
    takes,
    teleprompterSettings.autoScroll,
  ]);

  const stopRecording = useCallback(() => {
    const recorder = mediaRecorderRef.current;
    if (!recorder || recorder.state === "inactive") {
      return;
    }

    setIsRecording(false);
    setIsFinalizingTake(true);
    clearRecordingInterval();
    stopTeleprompter();
    showNotification("info", "جاري إنهاء الملف وتحليل التسجيل...");

    try {
      recorder.stop();
    } catch {
      pendingTakeRef.current = null;
      setIsFinalizingTake(false);
      showNotification("error", "تعذر إيقاف التسجيل بشكل صحيح.");
    }
  }, [clearRecordingInterval, showNotification, stopTeleprompter]);

  const deleteTake = useCallback(
    (takeId: string) => {
      revokeTakeResources(takeId);
      setTakes((previous) => previous.filter((take) => take.id !== takeId));
      showNotification("info", "تم حذف التسجيل المختار.");
    },
    [revokeTakeResources, showNotification],
  );

  const addManualNote = useCallback(
    (takeId: string) => {
      const draft = manualNoteDrafts[takeId]?.trim();
      if (!draft) {
        showNotification("error", "اكتب الملاحظة أولاً قبل إضافتها.");
        return;
      }

      const noteType = manualNoteTypes[takeId] ?? "improvement";

      setTakes((previous) =>
        previous.map((take) => {
          if (take.id !== takeId) {
            return take;
          }

          const manualNote: TakeNote = {
            id: `manual-${Date.now()}`,
            timestamp: Math.round(take.duration / 2),
            type: noteType,
            severity: "neutral",
            content: draft,
            autoGenerated: false,
          };

          return {
            ...take,
            notes: [manualNote, ...take.notes],
          };
        }),
      );

      setManualNoteDrafts((previous) => ({
        ...previous,
        [takeId]: "",
      }));
      showNotification("success", "تمت إضافة الملاحظة اليدوية.");
    },
    [manualNoteDrafts, manualNoteTypes, showNotification],
  );

  const exportTake = useCallback(
    async (takeId: string) => {
      const take = takes.find((currentTake) => currentTake.id === takeId);
      const blob = blobRegistryRef.current.get(takeId);

      if (!take || !blob) {
        showNotification(
          "error",
          "هذا التسجيل متاح كبيانات وصفية فقط. أعد التسجيل للحصول على ملف قابل للتنزيل.",
        );
        return;
      }

      setExportingTakeId(takeId);
      setExportProgress(15);
      await delay(80);

      const recordedExtension = inferExtensionFromMimeType(
        take.mimeType || blob.type,
      );
      const selectedExtension = exportSettings.format;
      const finalExtension =
        selectedExtension === recordedExtension
          ? selectedExtension
          : recordedExtension;
      const fileName = buildExportFileName({
        actorName: exportSettings.actorName || "actor",
        projectName: exportSettings.projectName || "self-tape",
        roleName: exportSettings.roleName || "scene",
        takeName: take.name,
        extension: finalExtension,
      });

      setExportProgress(55);
      await delay(80);

      const downloadUrl = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = downloadUrl;
      anchor.download = fileName;
      anchor.rel = "noopener";
      anchor.click();

      setExportProgress(100);
      setTakes((previous) =>
        previous.map((currentTake) =>
          currentTake.id === takeId
            ? {
                ...currentTake,
                status: "exported",
              }
            : currentTake,
        ),
      );

      setTimeout(() => URL.revokeObjectURL(downloadUrl), 1000);
      const exportSummary =
        selectedExtension === finalExtension
          ? `تم تنزيل ${take.name} بنجاح.`
          : `تم تنزيل ${take.name} بصيغة ${finalExtension} لأن الملف الأصلي سُجِّل بهذه الصيغة.`;
      const slateNotice = exportSettings.includeSlate
        ? " تم تضمين بيانات السليت داخل اسم الملف وإعدادات التصدير، لا داخل الصورة نفسها."
        : "";

      showNotification("success", `${exportSummary}${slateNotice}`);
      await delay(120);
      setExportingTakeId(null);
      setExportProgress(0);
    },
    [exportSettings, showNotification, takes],
  );

  const leftTake = availableTakes.find(
    (take) => take.id === comparisonView.leftTakeId,
  );
  const rightTake = availableTakes.find(
    (take) => take.id === comparisonView.rightTakeId,
  );
  const notesTake = availableTakes.find((take) => take.id === notesTakeId);

  return (
    <div
      className="min-h-screen bg-gradient-to-bl from-slate-900 via-purple-900 to-slate-900"
      dir="rtl"
    >
      <header className="border-b border-purple-500/30 bg-black/30 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-red-500 to-pink-600">
                <span className="text-2xl">🎥</span>
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white">
                  Self-Tape Suite
                </h1>
                <p className="text-sm text-purple-300">
                  استوديو التسجيل الذاتي الاحترافي
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3">
              <Badge variant="outline" className="border-green-500 text-green-400">
                تشغيل محلي
              </Badge>
              <Badge
                variant="outline"
                className="border-purple-500/60 text-purple-300"
              >
                {SELF_TAPE_STORAGE_KEY}
              </Badge>
              <Button
                variant="outline"
                className="border-purple-500 text-purple-300 hover:bg-purple-500/20"
                onClick={() => {
                  window.location.href = "/actorai-arabic";
                }}
              >
                العودة للرئيسية
              </Button>
            </div>
          </div>
        </div>
      </header>

      {notification && (
        <div className="fixed left-1/2 top-20 z-50 -translate-x-1/2">
          <Alert
            className={`${
              notification.type === "success"
                ? "border-green-500 bg-green-500/20 text-green-300"
                : notification.type === "error"
                  ? "border-red-500 bg-red-500/20 text-red-300"
                  : "border-blue-500 bg-blue-500/20 text-blue-300"
            }`}
          >
            <AlertDescription>{notification.message}</AlertDescription>
          </Alert>
        </div>
      )}

      <main className="container mx-auto px-4 py-6">
        <div className="mb-6 flex flex-wrap gap-2">
          {[
            { id: "teleprompter", label: "📜 Teleprompter" },
            { id: "recorder", label: "🎬 التسجيل" },
            { id: "comparison", label: "⚖️ المقارنة" },
            { id: "notes", label: "📝 الملاحظات" },
            { id: "export", label: "📤 التصدير" },
          ].map((tool) => (
            <Button
              key={tool.id}
              variant={activeTool === tool.id ? "default" : "outline"}
              className={
                activeTool === tool.id
                  ? "bg-purple-600 text-white hover:bg-purple-700"
                  : "border-purple-500/50 text-purple-300 hover:bg-purple-500/20"
              }
              onClick={() => setActiveTool(tool.id as ActiveTool)}
            >
              {tool.label}
            </Button>
          ))}
        </div>

        {activeTool === "teleprompter" && (
          <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white">⚙️ إعدادات التلقين</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <Label className="text-purple-300">
                    سرعة التمرير: {teleprompterSettings.speed}%
                  </Label>
                  <Slider
                    value={[teleprompterSettings.speed]}
                    min={10}
                    max={100}
                    step={5}
                    onValueChange={([value]) =>
                      setTeleprompterSettings((previous) => ({
                        ...previous,
                        speed: value ?? previous.speed,
                      }))
                    }
                  />
                </div>

                <div className="space-y-2">
                  <Label className="text-purple-300">
                    حجم الخط: {teleprompterSettings.fontSize}px
                  </Label>
                  <Slider
                    value={[teleprompterSettings.fontSize]}
                    min={18}
                    max={72}
                    step={2}
                    onValueChange={([value]) =>
                      setTeleprompterSettings((previous) => ({
                        ...previous,
                        fontSize: value ?? previous.fontSize,
                      }))
                    }
                  />
                </div>

                <div className="space-y-2">
                  <Label className="text-purple-300">
                    العد التنازلي: {teleprompterSettings.countdownSeconds} ثوان
                  </Label>
                  <Slider
                    value={[teleprompterSettings.countdownSeconds]}
                    min={0}
                    max={10}
                    step={1}
                    onValueChange={([value]) =>
                      setTeleprompterSettings((previous) => ({
                        ...previous,
                        countdownSeconds: value ?? previous.countdownSeconds,
                      }))
                    }
                  />
                </div>

                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Label className="text-purple-300">وضع المرآة</Label>
                    <Button
                      variant="outline"
                      size="sm"
                      className={
                        teleprompterSettings.mirrorMode
                          ? "border-purple-600 bg-purple-600 text-white"
                          : "border-purple-500/50 text-white"
                      }
                      onClick={() =>
                        setTeleprompterSettings((previous) => ({
                          ...previous,
                          mirrorMode: !previous.mirrorMode,
                        }))
                      }
                    >
                      {teleprompterSettings.mirrorMode ? "✓ مفعل" : "معطل"}
                    </Button>
                  </div>

                  <div className="flex items-center justify-between">
                    <Label className="text-purple-300">
                      تمييز السطر الحالي
                    </Label>
                    <Button
                      variant="outline"
                      size="sm"
                      className={
                        teleprompterSettings.highlightCurrentLine
                          ? "border-purple-600 bg-purple-600 text-white"
                          : "border-purple-500/50 text-white"
                      }
                      onClick={() =>
                        setTeleprompterSettings((previous) => ({
                          ...previous,
                          highlightCurrentLine: !previous.highlightCurrentLine,
                        }))
                      }
                    >
                      {teleprompterSettings.highlightCurrentLine
                        ? "✓ مفعل"
                        : "معطل"}
                    </Button>
                  </div>
                </div>

                <div className="flex gap-2 pt-2">
                  {!teleprompterRunning ? (
                    <Button
                      className="flex-1 bg-green-600 text-white hover:bg-green-700"
                      onClick={startTeleprompter}
                    >
                      {countdown > 0 ? `${countdown}...` : "▶️ تشغيل"}
                    </Button>
                  ) : (
                    <Button
                      className="flex-1 bg-yellow-600 text-white hover:bg-yellow-700"
                      onClick={stopTeleprompter}
                    >
                      ⏸️ إيقاف مؤقت
                    </Button>
                  )}
                  <Button
                    variant="outline"
                    className="border-purple-500/50 text-purple-300"
                    onClick={resetTeleprompter}
                  >
                    🔄 إعادة
                  </Button>
                </div>
              </CardContent>
            </Card>

            <Card className="bg-black border-purple-500/30 lg:col-span-2">
              <CardContent className="p-0">
                <div
                  className={`relative min-h-[500px] overflow-hidden ${
                    teleprompterSettings.mirrorMode ? "scale-x-[-1]" : ""
                  }`}
                >
                  {countdown > 0 && (
                    <div className="absolute inset-0 z-10 flex items-center justify-center bg-black/80">
                      <span className="text-9xl font-bold text-purple-500">
                        {countdown}
                      </span>
                    </div>
                  )}

                  <div className="absolute left-0 right-0 top-0 h-1 bg-purple-900">
                    <div
                      className="h-full bg-purple-500 transition-all duration-100"
                      style={{ width: `${teleprompterPosition}%` }}
                    />
                  </div>

                  <div
                    className="p-8 text-white transition-transform duration-100"
                    style={{
                      fontSize: `${teleprompterSettings.fontSize}px`,
                      transform: `translateY(-${teleprompterPosition * 3}px)`,
                    }}
                  >
                    {scriptText.split("\n").map((line, index, source) => {
                      const lineProgress =
                        (index / Math.max(source.length - 1, 1)) * 100;
                      const isCurrentLine =
                        teleprompterSettings.highlightCurrentLine &&
                        Math.abs(lineProgress - teleprompterPosition) < 10;

                      return (
                        <p
                          key={`${line}-${index}`}
                          className={`mb-4 leading-relaxed transition-all duration-300 ${
                            isCurrentLine
                              ? "rounded-lg bg-yellow-500/10 px-4 py-2 text-yellow-300"
                              : lineProgress < teleprompterPosition
                                ? "text-gray-500"
                                : "text-white"
                          }`}
                        >
                          {line || "\u00A0"}
                        </p>
                      );
                    })}
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="bg-slate-800/50 border-purple-500/30 lg:col-span-3">
              <CardHeader>
                <CardTitle className="text-white">✏️ النص المراد قراءته</CardTitle>
                <CardDescription className="text-purple-300">
                  اكتب النص الذي تريد استخدامه داخل جلسة السيلف تيب.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <Textarea
                  value={scriptText}
                  onChange={(event) => setScriptText(event.target.value)}
                  className="min-h-[220px] border-purple-500/30 bg-slate-900/50 text-lg text-white"
                  placeholder="أدخل نص المشهد هنا..."
                />
              </CardContent>
            </Card>
          </div>
        )}

        {activeTool === "recorder" && (
          <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white">🎬 استوديو التسجيل</CardTitle>
                <CardDescription className="text-purple-300">
                  معاينة حية من الكاميرا مع تسجيل فعلي عبر المتصفح.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {!mediaCaptureSupported && (
                  <Alert className="border-yellow-500/40 bg-yellow-500/10 text-yellow-200">
                    <AlertDescription>
                      هذه البيئة لا تدعم التسجيل الفعلي. ما يزال بإمكانك استعراض
                      الواجهة، لكن التسجيل سيتطلب متصفحاً حديثاً.
                    </AlertDescription>
                  </Alert>
                )}

                {cameraError && (
                  <Alert className="border-red-500/40 bg-red-500/10 text-red-200">
                    <AlertDescription>{cameraError}</AlertDescription>
                  </Alert>
                )}

                <div className="relative aspect-video overflow-hidden rounded-xl border-2 border-purple-500/30 bg-black">
                  {cameraState === "ready" ? (
                    <video
                      ref={previewVideoRef}
                      autoPlay
                      muted
                      playsInline
                      className="h-full w-full object-cover"
                    />
                  ) : (
                    <div className="flex h-full items-center justify-center text-center">
                      <div>
                        <div className="mx-auto mb-4 flex h-24 w-24 items-center justify-center rounded-full bg-purple-500/20">
                          <span className="text-5xl">
                            {cameraState === "requesting" ? "⏳" : "📹"}
                          </span>
                        </div>
                        <p className="text-lg text-white">
                          {cameraState === "requesting"
                            ? "جاري طلب الإذن للوصول إلى الكاميرا..."
                            : "معاينة الكاميرا ستظهر هنا بعد التفعيل"}
                        </p>
                      </div>
                    </div>
                  )}

                  {isRecording && (
                    <>
                      <div className="absolute right-4 top-4 flex items-center gap-2 rounded-full bg-black/60 px-3 py-2">
                        <div className="h-3 w-3 rounded-full bg-red-500 animate-pulse" />
                        <span className="font-mono text-red-300">
                          {formatTime(recordingTime)}
                        </span>
                      </div>

                      <div className="absolute bottom-0 left-0 right-0 bg-black/70 p-3 text-center text-white">
                        <p className="line-clamp-2 text-lg">{currentPromptLine}</p>
                      </div>
                    </>
                  )}

                  {isFinalizingTake && (
                    <div className="absolute inset-0 flex items-center justify-center bg-black/70">
                      <div className="text-center text-white">
                        <div className="mx-auto mb-3 h-12 w-12 animate-spin rounded-full border-4 border-purple-500 border-t-transparent" />
                        <p>جاري إنهاء التسجيل وتحليل النتيجة...</p>
                      </div>
                    </div>
                  )}
                </div>

                <div className="grid grid-cols-1 gap-3 md:grid-cols-3">
                  <Button
                    variant="outline"
                    className="border-purple-500/50 text-purple-300 hover:bg-purple-500/20"
                    onClick={() => {
                      void requestCameraAccess();
                    }}
                    disabled={cameraState === "requesting" || isRecording}
                  >
                    📷 تفعيل الكاميرا
                  </Button>

                  {!isRecording ? (
                    <Button
                      className="bg-red-600 text-white hover:bg-red-700"
                      onClick={() => {
                        void startRecording();
                      }}
                      disabled={
                        cameraState === "requesting" ||
                        isFinalizingTake ||
                        !mediaCaptureSupported
                      }
                    >
                      🎬 بدء التسجيل
                    </Button>
                  ) : (
                    <Button
                      className="bg-gray-700 text-white hover:bg-gray-800"
                      onClick={stopRecording}
                    >
                      ⏹️ إنهاء التسجيل
                    </Button>
                  )}

                  <Button
                    variant="outline"
                    className="border-blue-500/50 text-blue-300 hover:bg-blue-500/20"
                    onClick={resetTeleprompter}
                    disabled={isFinalizingTake}
                  >
                    📜 إعادة التلقين
                  </Button>
                </div>

                <div className="grid grid-cols-3 gap-4 border-t border-purple-500/30 pt-4">
                  <div className="text-center">
                    <p className="text-3xl font-bold text-purple-400">
                      {availableTakes.length}
                    </p>
                    <p className="text-sm text-gray-400">إجمالي التسجيلات</p>
                  </div>
                  <div className="text-center">
                    <p className="text-3xl font-bold text-green-400">
                      {bestScore}%
                    </p>
                    <p className="text-sm text-gray-400">أعلى تقييم</p>
                  </div>
                  <div className="text-center">
                    <p className="text-3xl font-bold text-blue-400">
                      {formatTime(totalDuration)}
                    </p>
                    <p className="text-sm text-gray-400">إجمالي الوقت</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white">
                  📋 التسجيلات ({availableTakes.length})
                </CardTitle>
                <CardDescription className="text-purple-300">
                  التسجيلات الحية تبقى قابلة للتصدير داخل الجلسة الحالية، بينما
                  تُحفظ البيانات الوصفية محلياً بين الزيارات.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="max-h-[560px] space-y-3 overflow-y-auto">
                  {availableTakes.map((take) => (
                    <div
                      key={take.id}
                      className="rounded-xl border border-purple-500/20 bg-slate-900/50 p-4 transition-all hover:border-purple-500/50"
                    >
                      <div className="mb-3 flex items-start justify-between gap-3">
                        <div>
                          <h4 className="flex items-center gap-2 font-medium text-white">
                            {take.name}
                            {take.source === "captured" ? (
                              <Badge className="bg-emerald-500/20 text-emerald-300">
                                جلسة حيّة
                              </Badge>
                            ) : (
                              <Badge className="bg-slate-700/60 text-slate-200">
                                نموذج
                              </Badge>
                            )}
                            {take.status === "exported" && (
                              <Badge className="bg-blue-500/20 text-blue-300">
                                مُصدَّر
                              </Badge>
                            )}
                          </h4>
                          <p className="text-sm text-gray-400">
                            {formatRecordedAt(take.recordedAt)} •{" "}
                            {formatTime(take.duration)}
                          </p>
                        </div>

                        <div className={`text-2xl font-bold ${getScoreColor(take.score)}`}>
                          {take.score ?? 0}%
                        </div>
                      </div>

                      {take.videoUrl ? (
                        <video
                          src={take.videoUrl}
                          controls
                          muted
                          className="mb-3 aspect-video w-full rounded-lg bg-black object-cover"
                        />
                      ) : (
                        <div className="mb-3 flex aspect-video items-center justify-center rounded-lg border border-dashed border-purple-500/20 bg-black/40 text-center text-sm text-gray-400">
                          <div>
                            <p>لا يوجد ملف فيديو محفوظ مع هذا التسجيل.</p>
                            <p>البيانات الوصفية محفوظة، لكن التصدير يتطلب جلسة حيّة.</p>
                          </div>
                        </div>
                      )}

                      <div className="mb-3 text-sm text-gray-300">
                        <p>{take.notes[0]?.content ?? "لا توجد ملاحظات بعد."}</p>
                      </div>

                      <div className="flex gap-2">
                        <Button
                          size="sm"
                          variant="outline"
                          className="flex-1 border-purple-500/50 text-purple-300 hover:bg-purple-500/20"
                          onClick={() => {
                            setActiveTool("notes");
                            setNotesTakeId(take.id);
                          }}
                        >
                          📝 الملاحظات
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="flex-1 border-green-500/50 text-green-300 hover:bg-green-500/20"
                          onClick={() => {
                            void exportTake(take.id);
                          }}
                          disabled={!blobRegistryRef.current.has(take.id)}
                        >
                          📤 تصدير
                        </Button>
                        <Button
                          size="sm"
                          variant="outline"
                          className="border-red-500/50 text-red-300 hover:bg-red-500/20"
                          onClick={() => deleteTake(take.id)}
                        >
                          🗑️
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {activeTool === "comparison" && (
          <div className="space-y-6">
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white">
                  ⚖️ مقارنة التسجيلات
                </CardTitle>
                <CardDescription className="text-purple-300">
                  قارن بين تسجيلين بصرياً وعددياً لاختيار النسخة الأقوى.
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 items-end gap-4 md:grid-cols-3">
                  <div>
                    <Label className="mb-2 block text-purple-300">
                      التسجيل الأيسر
                    </Label>
                    <Select
                      value={comparisonView.leftTakeId ?? ""}
                      onValueChange={(value) =>
                        setComparisonView((previous) => ({
                          ...previous,
                          leftTakeId: value,
                        }))
                      }
                    >
                      <SelectTrigger className="border-purple-500/30 bg-slate-900/50 text-white">
                        <SelectValue placeholder="اختر تسجيلاً" />
                      </SelectTrigger>
                      <SelectContent className="border-purple-500/30 bg-slate-900">
                        {availableTakes.map((take) => (
                          <SelectItem
                            key={take.id}
                            value={take.id}
                            className="text-white"
                          >
                            {take.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="text-center">
                    <Button
                      variant="outline"
                      className={
                        comparisonView.syncPlayback
                          ? "border-purple-600 bg-purple-600 text-white"
                          : "border-purple-500/50 text-white"
                      }
                      onClick={() =>
                        setComparisonView((previous) => ({
                          ...previous,
                          syncPlayback: !previous.syncPlayback,
                        }))
                      }
                    >
                      {comparisonView.syncPlayback ? "🔗 متزامن" : "🔓 منفصل"}
                    </Button>
                  </div>

                  <div>
                    <Label className="mb-2 block text-purple-300">
                      التسجيل الأيمن
                    </Label>
                    <Select
                      value={comparisonView.rightTakeId ?? ""}
                      onValueChange={(value) =>
                        setComparisonView((previous) => ({
                          ...previous,
                          rightTakeId: value,
                        }))
                      }
                    >
                      <SelectTrigger className="border-purple-500/30 bg-slate-900/50 text-white">
                        <SelectValue placeholder="اختر تسجيلاً" />
                      </SelectTrigger>
                      <SelectContent className="border-purple-500/30 bg-slate-900">
                        {availableTakes.map((take) => (
                          <SelectItem
                            key={take.id}
                            value={take.id}
                            className="text-white"
                          >
                            {take.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </CardContent>
            </Card>

            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              {[leftTake, rightTake].map((take, index) => (
                <Card
                  key={take?.id ?? `empty-${index}`}
                  className="bg-slate-800/50 border-purple-500/30"
                >
                  <CardHeader className="pb-3">
                    <CardTitle className="text-lg text-white">
                      {take?.name ?? "اختر تسجيلاً"}
                    </CardTitle>
                    {take && (
                      <CardDescription className="text-purple-300">
                        {formatRecordedAt(take.recordedAt)}
                      </CardDescription>
                    )}
                  </CardHeader>
                  <CardContent className="space-y-4">
                    {take?.videoUrl ? (
                      <video
                        src={take.videoUrl}
                        controls
                        muted={!comparisonView.syncPlayback}
                        className="aspect-video w-full rounded-lg bg-black object-cover"
                      />
                    ) : (
                      <div className="flex aspect-video items-center justify-center rounded-lg border border-dashed border-purple-500/20 bg-black/40 text-center text-gray-400">
                        <div>
                          <p>لا يوجد ملف فيديو مباشر لهذا الجانب.</p>
                          <p className="text-sm">
                            ستبقى المقارنة الرقمية متاحة من خلال التقييمات والملاحظات.
                          </p>
                        </div>
                      </div>
                    )}

                    {take && (
                      <div className="space-y-2 text-sm">
                        <div className="flex justify-between">
                          <span className="text-gray-400">التقييم</span>
                          <span className={`font-bold ${getScoreColor(take.score)}`}>
                            {take.score ?? 0}%
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-400">المدة</span>
                          <span className="text-white">
                            {formatTime(take.duration)}
                          </span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-gray-400">الملاحظات</span>
                          <span className="text-purple-300">
                            {take.notes.length} ملاحظة
                          </span>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              ))}
            </div>

            {leftTake && rightTake && (
              <Card className="bg-slate-800/50 border-purple-500/30">
                <CardHeader>
                  <CardTitle className="text-white">📊 ملخص المقارنة</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
                    <div className="rounded-xl bg-slate-900/50 p-4 text-center">
                      <p className="mb-2 text-sm text-gray-400">فرق التقييم</p>
                      <p className="text-3xl font-bold text-green-400">
                        {(rightTake.score ?? 0) - (leftTake.score ?? 0) > 0
                          ? "+"
                          : ""}
                        {(rightTake.score ?? 0) - (leftTake.score ?? 0)}%
                      </p>
                    </div>
                    <div className="rounded-xl bg-slate-900/50 p-4 text-center">
                      <p className="mb-2 text-sm text-gray-400">فرق المدة</p>
                      <p className="text-3xl font-bold text-purple-400">
                        {Math.abs(rightTake.duration - leftTake.duration)}ث
                      </p>
                    </div>
                    <div className="rounded-xl bg-slate-900/50 p-4 text-center">
                      <p className="mb-2 text-sm text-gray-400">النسخة الأفضل</p>
                      <p className="text-xl font-bold text-yellow-400">
                        {(rightTake.score ?? 0) > (leftTake.score ?? 0)
                          ? rightTake.name
                          : leftTake.name}
                      </p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>
        )}

        {activeTool === "notes" && (
          <Card className="bg-slate-800/50 border-purple-500/30">
            <CardHeader>
              <CardTitle className="text-white">
                📝 الملاحظات وتحسين الأداء
              </CardTitle>
              <CardDescription className="text-purple-300">
                الملاحظات التلقائية تُبنى من نتيجة التسجيل، ويمكنك إضافة ملاحظاتك
                اليدوية فوقها.
              </CardDescription>
            </CardHeader>
            <CardContent>
              {notesTake ? (
                <Tabs
                  value={notesTakeId ?? undefined}
                  onValueChange={(value) => setNotesTakeId(value)}
                >
                  <TabsList className="mb-4 h-auto flex-wrap gap-2 border border-purple-500/30 bg-slate-900/50 p-2">
                    {availableTakes.map((take) => (
                      <TabsTrigger
                        key={take.id}
                        value={take.id}
                        className="text-white data-[state=active]:bg-purple-600"
                      >
                        {take.name}
                      </TabsTrigger>
                    ))}
                  </TabsList>

                  {availableTakes.map((take) => (
                    <TabsContent key={take.id} value={take.id}>
                      <div className="space-y-6">
                        <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
                          <div className="rounded-xl bg-slate-900/50 p-4 text-center">
                            <p className="text-sm text-gray-400">التقييم العام</p>
                            <p className={`text-3xl font-bold ${getScoreColor(take.score)}`}>
                              {take.score ?? 0}%
                            </p>
                          </div>
                          <div className="rounded-xl bg-slate-900/50 p-4 text-center">
                            <p className="text-sm text-gray-400">إيجابي</p>
                            <p className="text-3xl font-bold text-green-400">
                              {
                                take.notes.filter(
                                  (note) => note.severity === "positive",
                                ).length
                              }
                            </p>
                          </div>
                          <div className="rounded-xl bg-slate-900/50 p-4 text-center">
                            <p className="text-sm text-gray-400">تحتاج تحسين</p>
                            <p className="text-3xl font-bold text-yellow-400">
                              {
                                take.notes.filter(
                                  (note) => note.severity === "needs_work",
                                ).length
                              }
                            </p>
                          </div>
                          <div className="rounded-xl bg-slate-900/50 p-4 text-center">
                            <p className="text-sm text-gray-400">المدة</p>
                            <p className="text-3xl font-bold text-purple-400">
                              {formatTime(take.duration)}
                            </p>
                          </div>
                        </div>

                        <div className="space-y-3">
                          {take.notes.map((note) => (
                            <div
                              key={note.id}
                              className={`rounded-xl border p-4 ${getSeverityContainerClass(
                                note.severity,
                              )}`}
                            >
                              <div className="mb-2 flex items-start justify-between gap-3">
                                <div className="flex items-center gap-2">
                                  <Badge className={NOTE_TYPE_COLOR[note.type]}>
                                    {NOTE_TYPE_LABELS[note.type]}
                                  </Badge>
                                  <span className="text-sm text-gray-400">
                                    @{formatTime(note.timestamp)}
                                  </span>
                                </div>
                                <Badge
                                  variant="outline"
                                  className="border-purple-500/50 text-purple-300"
                                >
                                  {note.autoGenerated ? "محلي" : "يدوي"}
                                </Badge>
                              </div>
                              <p className="text-white">{note.content}</p>
                            </div>
                          ))}
                        </div>

                        <div className="rounded-xl border border-purple-500/30 bg-slate-900/50 p-4">
                          <Label className="mb-3 block text-purple-300">
                            أضف ملاحظة يدوية
                          </Label>
                          <div className="grid grid-cols-1 gap-3 md:grid-cols-[220px_1fr_auto]">
                            <Select
                              value={manualNoteTypes[take.id] ?? "improvement"}
                              onValueChange={(value) =>
                                setManualNoteTypes((previous) => ({
                                  ...previous,
                                  [take.id]: value as NoteType,
                                }))
                              }
                            >
                              <SelectTrigger className="border-purple-500/30 bg-slate-800/50 text-white">
                                <SelectValue />
                              </SelectTrigger>
                              <SelectContent className="border-purple-500/30 bg-slate-900">
                                {Object.entries(NOTE_TYPE_LABELS).map(
                                  ([value, label]) => (
                                    <SelectItem
                                      key={value}
                                      value={value}
                                      className="text-white"
                                    >
                                      {label}
                                    </SelectItem>
                                  ),
                                )}
                              </SelectContent>
                            </Select>

                            <Input
                              value={manualNoteDrafts[take.id] ?? ""}
                              onChange={(event) =>
                                setManualNoteDrafts((previous) => ({
                                  ...previous,
                                  [take.id]: event.target.value,
                                }))
                              }
                              placeholder="اكتب الملاحظة التي تريد حفظها مع هذا التسجيل"
                              className="border-purple-500/30 bg-slate-800/50 text-white"
                            />

                            <Button
                              className="bg-purple-600 text-white hover:bg-purple-700"
                              onClick={() => addManualNote(take.id)}
                            >
                              إضافة
                            </Button>
                          </div>
                        </div>
                      </div>
                    </TabsContent>
                  ))}
                </Tabs>
              ) : (
                <div className="py-12 text-center text-gray-400">
                  لا توجد تسجيلات لعرض ملاحظاتها بعد.
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {activeTool === "export" && (
          <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white">⚙️ إعدادات التصدير</CardTitle>
                <CardDescription className="text-purple-300">
                  التصدير الحالي ينزل الملف الأصلي المسجل كما التقطه المتصفح، مع
                  استخدام الاسم المنظف وبيانات السليت داخل اسم الملف.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <Label className="text-purple-300">جودة الإخراج</Label>
                  <Select
                    value={exportSettings.quality}
                    onValueChange={(value) =>
                      setExportSettings((previous) => ({
                        ...previous,
                        quality: value as ExportSettings["quality"],
                      }))
                    }
                  >
                    <SelectTrigger className="border-purple-500/30 bg-slate-900/50 text-white">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="border-purple-500/30 bg-slate-900">
                      <SelectItem value="casting" className="text-white">
                        Casting
                      </SelectItem>
                      <SelectItem value="high" className="text-white">
                        High
                      </SelectItem>
                      <SelectItem value="medium" className="text-white">
                        Medium
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label className="text-purple-300">الصيغة المفضلة</Label>
                  <Select
                    value={exportSettings.format}
                    onValueChange={(value) =>
                      setExportSettings((previous) => ({
                        ...previous,
                        format: value as ExportSettings["format"],
                      }))
                    }
                  >
                    <SelectTrigger className="border-purple-500/30 bg-slate-900/50 text-white">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="border-purple-500/30 bg-slate-900">
                      <SelectItem value="webm" className="text-white">
                        WebM
                      </SelectItem>
                      <SelectItem value="mp4" className="text-white">
                        MP4
                      </SelectItem>
                      <SelectItem value="mov" className="text-white">
                        MOV
                      </SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="rounded-xl bg-slate-900/50 p-4">
                  <div className="mb-4 flex items-center justify-between">
                    <Label className="text-purple-300">تضمين بيانات السليت</Label>
                    <Button
                      variant="outline"
                      size="sm"
                      className={
                        exportSettings.includeSlate
                          ? "border-purple-600 bg-purple-600 text-white"
                          : "border-purple-500/50 text-white"
                      }
                      onClick={() =>
                        setExportSettings((previous) => ({
                          ...previous,
                          includeSlate: !previous.includeSlate,
                        }))
                      }
                    >
                      {exportSettings.includeSlate ? "✓ مفعل" : "معطل"}
                    </Button>
                  </div>

                  {exportSettings.includeSlate && (
                    <div className="space-y-4">
                      <div>
                        <Label className="text-sm text-purple-300">
                          اسم الممثل
                        </Label>
                        <Input
                          value={exportSettings.actorName}
                          onChange={(event) =>
                            setExportSettings((previous) => ({
                              ...previous,
                              actorName: event.target.value,
                            }))
                          }
                          className="mt-1 border-purple-500/30 bg-slate-800/50 text-white"
                          placeholder="اسم الممثل"
                        />
                      </div>
                      <div>
                        <Label className="text-sm text-purple-300">
                          اسم المشروع
                        </Label>
                        <Input
                          value={exportSettings.projectName}
                          onChange={(event) =>
                            setExportSettings((previous) => ({
                              ...previous,
                              projectName: event.target.value,
                            }))
                          }
                          className="mt-1 border-purple-500/30 bg-slate-800/50 text-white"
                          placeholder="اسم الفيلم أو المشروع"
                        />
                      </div>
                      <div>
                        <Label className="text-sm text-purple-300">
                          اسم الدور
                        </Label>
                        <Input
                          value={exportSettings.roleName}
                          onChange={(event) =>
                            setExportSettings((previous) => ({
                              ...previous,
                              roleName: event.target.value,
                            }))
                          }
                          className="mt-1 border-purple-500/30 bg-slate-800/50 text-white"
                          placeholder="اسم الشخصية"
                        />
                      </div>
                      <div>
                        <Label className="text-sm text-purple-300">
                          الوكالة
                        </Label>
                        <Input
                          value={exportSettings.agencyName}
                          onChange={(event) =>
                            setExportSettings((previous) => ({
                              ...previous,
                              agencyName: event.target.value,
                            }))
                          }
                          className="mt-1 border-purple-500/30 bg-slate-800/50 text-white"
                          placeholder="اختياري"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label className="text-sm text-purple-300">
                          مدة السليت: {exportSettings.slateDuration} ثوان
                        </Label>
                        <Slider
                          value={[exportSettings.slateDuration]}
                          min={3}
                          max={10}
                          step={1}
                          onValueChange={([value]) =>
                            setExportSettings((previous) => ({
                              ...previous,
                              slateDuration:
                                value ?? previous.slateDuration,
                            }))
                          }
                        />
                      </div>
                    </div>
                  )}
                </div>

                {exportingTakeId && (
                  <div className="rounded-xl border border-purple-500/30 bg-slate-900/50 p-4">
                    <p className="mb-3 text-white">
                      جاري إعداد الملف للتنزيل...
                    </p>
                    <Progress value={exportProgress} className="h-3" />
                    <p className="mt-2 text-sm text-purple-300">
                      {exportProgress}%
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>

            <Card className="bg-slate-800/50 border-purple-500/30">
              <CardHeader>
                <CardTitle className="text-white">📤 تنزيل التسجيلات</CardTitle>
                <CardDescription className="text-purple-300">
                  التسجيلات التي تحتوي على ملف فيديو حي فقط ستكون قابلة للتنزيل.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                {availableTakes.map((take) => {
                  const canDownload = blobRegistryRef.current.has(take.id);
                  return (
                    <div
                      key={take.id}
                      className="rounded-xl border border-purple-500/20 bg-slate-900/50 p-4"
                    >
                      <div className="flex items-center justify-between gap-4">
                        <div>
                          <h4 className="font-medium text-white">{take.name}</h4>
                          <p className="text-sm text-gray-400">
                            {formatTime(take.duration)} • {take.score ?? 0}%
                          </p>
                        </div>

                        <Button
                          className="bg-green-600 text-white hover:bg-green-700"
                          onClick={() => {
                            void exportTake(take.id);
                          }}
                          disabled={!canDownload || exportingTakeId === take.id}
                        >
                          {canDownload ? "📤 تنزيل" : "غير متاح"}
                        </Button>
                      </div>

                      {!canDownload && (
                        <p className="mt-3 text-sm text-yellow-300">
                          هذا التسجيل محفوظ كمرجع وصفي فقط بعد إعادة التحميل، لذا
                          لا يملك ملف فيديو صالحاً للتنزيل.
                        </p>
                      )}
                    </div>
                  );
                })}

                {bestExportableTake && (
                  <div className="border-t border-purple-500/30 pt-4">
                    <Button
                      className="w-full bg-purple-600 text-white hover:bg-purple-700"
                      onClick={() => {
                        void exportTake(bestExportableTake.id);
                      }}
                      disabled={Boolean(exportingTakeId)}
                    >
                      ⭐ تنزيل أفضل تسجيل قابل للتصدير
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        )}
      </main>

      <footer className="mt-8 border-t border-purple-500/30 bg-black/30">
        <div className="container mx-auto flex flex-col items-center justify-between gap-4 px-4 py-6 md:flex-row">
          <p className="text-sm text-gray-400">
            Self-Tape Suite © 2025 - جزء من منصة ActorAI العربية
          </p>
          <div className="flex items-center gap-4">
            <Badge variant="outline" className="border-purple-500/50 text-purple-300">
              تخزين وصفي محلي
            </Badge>
            <Badge variant="outline" className="border-green-500/50 text-green-300">
              v2
            </Badge>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default SelfTapeSuite;
